kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
    app: nginx
    visualize: "true"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: proxied    
